---
# 模板商城初始化(服务启动时会进行数据检查，如果存在则不再初始化)
- identify: "simple_crud_table_tpl"
  scope: "default"
  icon: "fa fa-table"
  name: "简单的crud模板"
  desc: "带查询功能的增删查改表格模板"
  source: |
    {
        "$schema": "http://amis.baidu.com/v2/schemas/page.json#",
        "type": "page",
        "title": "默认标题",
        "body": {
            "name": "crud-manage-table",
            "type": "crud",
            "draggable": false,
            "pageField": "current",
            "perPageField": "pageSize",
            "syncLocation": false,
            "api": {
                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/query",
                "method": "get",
                "headers": {
                    "Authorization": "${_authorization}"
                },
                "data": {
                    "&": "$$"
                }
            },
            "keepItemSelectionOnPageChange": true,
            "filter": {
                "title": "条件搜索",
                "visibleOn": "acl.can('/tools/tpl_mall:query')",
                "submitText": "",
                "controls": [
                    {
                        "type": "text",
                        "name": "queryValue",
                        "placeholder": "搜索提示",
                        "addOn": {
                            "label": "搜索",
                            "type": "submit"
                        }
                    }
                ]
            },
            "filterTogglable": true,
            "headerToolbar": [
                {
                    "type": "button",
                    "actionType": "drawer",
                    "label": "新增",
                    "icon": "fa fa-plus pull-left",
                    "primary": true,
                    "visibleOn": "acl.can('/tools/tpl_mall:add')",
                    "drawer": {
                        "title": "新增",
                        "position": "left",
                        "size": "lg",
                        "resizable": true,
                        "body": {
                            "type": "form",
                            "name": "sample-edit-form",
                            "api": {
                                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/add",
                                "method": "post",
                                "headers": {
                                    "Authorization": "${_authorization}"
                                }
                            },
                            "controls": [
                                {
                                    "name": "user_name",
                                    "label": "用户名",
                                    "sortable": true,
                                    "type": "text",
                                    "required": true
                                },
                                {
                                    "name": "password",
                                    "label": "密码",
                                    "sortable": true,
                                    "type": "password",
                                    "required": true
                                },
                                {
                                    "name": "real_name",
                                    "label": "真实姓名",
                                    "sortable": true,
                                    "type": "text",
                                    "required": true
                                },
                                {
                                    "type": "radios",
                                    "name": "status",
                                    "label": "用户状态",
                                    "inline": true,
                                    "value": 1,
                                    "options": [
                                        {
                                            "label": "正常",
                                            "value": 1
                                        },
                                        {
                                            "label": "停用",
                                            "value": 2
                                        }
                                    ]
                                },
                                {
                                    "name": "email",
                                    "label": "邮箱",
                                    "sortable": true,
                                    "type": "text",
                                    "toggled": true
                                },
                                {
                                    "name": "phone",
                                    "label": "手机号",
                                    "sortable": true,
                                    "type": "text",
                                    "toggled": true
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "columns-toggler",
                    "align": "right"
                },
                {
                    "type": "pagination",
                    "align": "right"
                },
                {
                    "type": "filter-toggler",
                    "align": "right"
                }
            ],
            "footerToolbar": [
                "statistics",
                "switch-per-page",
                "pagination"
            ],
            "columns": [
                {
                    "name": "user_name",
                    "label": "用户名",
                    "sortable": true,
                    "type": "text"
                },
                {
                    "name": "real_name",
                    "label": "真实姓名",
                    "sortable": true,
                    "type": "text"
                },
                {
                    "name": "status",
                    "label": "用户状态",
                    "sortable": true,
                    "type": "mapping",
                    "toggled": true,
                    "map": {
                        "1": "<span class='label label-success'>启用</span>",
                        "2": "<span class='label label-danger'>禁用</span>"
                    }
                },
                {
                    "name": "email",
                    "label": "邮箱",
                    "sortable": true,
                    "type": "text",
                    "toggled": true
                },
                {
                    "name": "phone",
                    "label": "手机号",
                    "sortable": true,
                    "type": "text",
                    "toggled": true
                },
                {
                    "name": "created_at",
                    "label": "创建时间",
                    "sortable": true,
                    "type": "date",
                    "format": "YYYY-MM-DD hh:mm:ss",
                    "toggled": true
                },
                {
                    "type": "operation",
                    "label": "操作",
                    "width": 200,
                    "visibleOn": "acl.can('/tools/tpl_mall:edit', '/tools/tpl_mall:delete')",
                    "buttons": [
                        {
                            "type": "button",
                            "icon": "fa fa-pencil",
                            "tooltip": "编辑",
                            "actionType": "drawer",
                            "visibleOn": "acl.can('/tools/tpl_mall:edit')",
                            "drawer": {
                                "position": "left",
                                "size": "lg",
                                "title": "编辑",
                                "resizable": true,
                                "body": {
                                    "type": "form",
                                    "name": "sample-edit-form",
                                    "api": {
                                        "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/edit/$id",
                                        "method": "put",
                                        "headers": {
                                            "Authorization": "${_authorization}"
                                        }
                                    },
                                    "controls": [
                                        {
                                            "name": "user_name",
                                            "label": "用户名",
                                            "sortable": true,
                                            "type": "text",
                                            "required": true
                                        },
                                        {
                                            "name": "password",
                                            "label": "密码",
                                            "sortable": true,
                                            "type": "password",
                                            "placeholder": "留空则不修改登录密码"
                                        },
                                        {
                                            "name": "real_name",
                                            "label": "真实姓名",
                                            "sortable": true,
                                            "type": "text",
                                            "required": true
                                        },
                                        {
                                            "type": "radios",
                                            "name": "status",
                                            "label": "用户状态",
                                            "inline": true,
                                            "value": 1,
                                            "options": [
                                                {
                                                    "label": "正常",
                                                    "value": 1
                                                },
                                                {
                                                    "label": "停用",
                                                    "value": 2
                                                }
                                            ]
                                        },
                                        {
                                            "name": "email",
                                            "label": "邮箱",
                                            "sortable": true,
                                            "type": "text",
                                            "toggled": true
                                        },
                                        {
                                            "name": "phone",
                                            "label": "手机号",
                                            "sortable": true,
                                            "type": "text",
                                            "toggled": true
                                        }
                                    ]
                                }
                            }
                        },
                        {
                            "type": "button",
                            "icon": "fa fa-times text-danger",
                            "actionType": "ajax",
                            "tooltip": "删除",
                            "confirmText": "您确认要删除?",
                            "visibleOn": "acl.can('/tools/tpl_mall:delete')",
                            "api": {
                                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/delete/$id",
                                "method": "delete",
                                "headers": {
                                    "Authorization": "${_authorization}"
                                }
                            }
                        }
                    ],
                    "toggled": true
                }
            ]
        }
    }
  mock_data:
    - path: add
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {}
        }
    - path: edit
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {}
        }
    - path: query
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {
                "count": 2,
                "rows": [
                    {
                        "user_name": "zhangshan",
                        "real_name": "张三",
                        "status": 1,
                        "email": "zhangshan@kingsoft.com",
                        "phone": "13800000000",
                        "created_at": 1595470299
                    },
                    {
                        "user_name": "lisi",
                        "real_name": "李四",
                        "status": 0,
                        "email": "lisi@kingsoft.com",
                        "phone": "13800000000",
                        "created_at": 1595470299
                    }
                ]
            }
        }
    - path: delete
      data: |
        {
          "status": 0,
          "msg": "",
          "data": {}
        }

  creator: "root"
  status: 1