---
# 模板商城初始化(服务启动时会进行数据检查，如果存在则不再初始化)
- identify: "simple_crud_table_tpl"
  scope: "default"
  icon: "fa fa-table"
  name: "简单的crud模板"
  desc: "带查询功能的增删查改表格模板"
  meta: |
    {
        "base": {
            "title": "默认标题"
        },
        "acl": {
            "search": "acl.can('*')",
            "add": "acl.can('*')",
            "operation": "acl.can('*')",
            "update": "acl.can('*')",
            "delete": "acl.can('*')"
        },
        "api": {
            "query": {
                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/query",
                "method": "get",
                "headers": {
                    "Authorization": "${_authorization}"
                },
                "data": {
                    "&": "$$"
                }
            },
            "create": {
                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/add",
                "method": "post",
                "headers": {
                    "Authorization": "${_authorization}"
                }
            },
            "update": {
                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/edit/$id",
                "method": "put",
                "headers": {
                    "Authorization": "${_authorization}"
                }
            },
            "delete": {
                "url": "${_page_schema_api|raw}/api/v1/tpl_mall.mock/simple_crud_table_tpl/delete/$id",
                "method": "delete",
                "headers": {
                    "Authorization": "${_authorization}"
                }
            }
        },
        "fields": {
            "user_name": {
                "name": "user_name",
                "label": "用户名",
                "sortable": true,
                "type": "text",
                "@create|@update": {
                    "required": true
                },
                "@list": {}
            },
            "password": {
                "name": "password",
                "label": "密码",
                "sortable": true,
                "type": "password",
                "@create": {
                    "required": true
                },
                "@update": {}
            },
            "real_name": {
                "name": "real_name",
                "label": "真实姓名",
                "sortable": true,
                "type": "text",
                "@create|@update": {
                    "required": true
                },
                "@list": {}
            },
            "status": {
                "name": "status",
                "label": "用户状态",
                "sortable": true,
                "type": "mapping",
                "toggled": true,
                "map": {
                    "1": "<span class='label label-success'>启用</span>",
                    "2": "<span class='label label-danger'>禁用</span>"
                },
                "@create|@update": {
                    "-map": true,
                    "-toggled": true,
                    "type": "radios",
                    "name": "status",
                    "label": "用户状态",
                    "inline": true,
                    "value": 1,
                    "required": true,
                    "options": [
                        {
                            "label": "正常",
                            "value": 1
                        },
                        {
                            "label": "停用",
                            "value": 2
                        }
                    ]
                },
                "@list": {}
            },
            "email": {
                "name": "email",
                "label": "邮箱",
                "sortable": true,
                "type": "text",
                "toggled": true,
                "@list": {},
                "@create|@update": {}
            },
            "phone": {
                "name": "phone",
                "label": "手机号",
                "sortable": true,
                "type": "text",
                "toggled": true,
                "@list": {},
                "@create|@update": {}
            },
            "created_at": {
                "name": "created_at",
                "label": "创建时间",
                "sortable": true,
                "type": "date",
                "format": "YYYY-MM-DD hh:mm:ss",
                "toggled": true,
                "@list": {}
            }
        }
    }
  source: |
    {
        "$schema": "http://amis.baidu.com/v2/schemas/page.json#",
        "type": "page",
        "title": "@meta.base.title",
        "body": {
            "name": "crud-manage-table",
            "type": "crud",
            "draggable": false,
            "pageField": "current",
            "perPageField": "pageSize",
            "syncLocation": false,
            "api": "@meta.api.query",
            "keepItemSelectionOnPageChange": true,
            "filter": {
                "title": "条件搜索",
                "visibleOn": "@meta.acl.search",
                "submitText": "",
                "controls": [
                    {
                        "type": "text",
                        "name": "queryValue",
                        "placeholder": "搜索提示",
                        "addOn": {
                            "label": "搜索",
                            "type": "submit"
                        }
                    }
                ]
            },
            "filterTogglable": true,
            "headerToolbar": [
                {
                    "type": "button",
                    "actionType": "drawer",
                    "label": "新增",
                    "icon": "fa fa-plus pull-left",
                    "primary": true,
                    "visibleOn": "@meta.acl.add",
                    "drawer": {
                        "title": "新增",
                        "position": "left",
                        "size": "lg",
                        "resizable": true,
                        "body": {
                            "type": "form",
                            "name": "sample-edit-form",
                            "api": "@meta.api.create",
                            "controls": "@meta.scene.create"
                        }
                    }
                },
                {
                    "type": "columns-toggler",
                    "align": "right"
                },
                {
                    "type": "pagination",
                    "align": "right"
                },
                {
                    "type": "filter-toggler",
                    "align": "right"
                }
            ],
            "footerToolbar": [
                "statistics",
                "switch-per-page",
                "pagination"
            ],
            "columns": [
                "@meta.scene.list|@expand",
                {
                    "type": "operation",
                    "label": "操作",
                    "width": 200,
                    "toggled": true,
                    "visibleOn": "@meta.acl.operation",
                    "buttons": [
                        {
                            "type": "button",
                            "icon": "fa fa-pencil",
                            "tooltip": "编辑",
                            "actionType": "drawer",
                            "visibleOn": "@meta.acl.update",
                            "drawer": {
                                "position": "left",
                                "size": "lg",
                                "title": "编辑",
                                "resizable": true,
                                "body": {
                                    "type": "form",
                                    "name": "sample-edit-form",
                                    "api": "@meta.api.update",
                                    "controls": "@meta.scene.update"
                                }
                            }
                        },
                        {
                            "type": "button",
                            "icon": "fa fa-times text-danger",
                            "actionType": "ajax",
                            "tooltip": "删除",
                            "confirmText": "您确认要删除?",
                            "visibleOn": "@meta.acl.delete",
                            "api": "@meta.api.delete"
                        }
                    ]
                }
            ]
        }
    }
  mock_data:
    - path: add
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {}
        }
    - path: edit
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {}
        }
    - path: query
      data: |
        {
        	"status": 0,
        	"msg": "",
        	"data": {
                "count": 2,
                "rows": [
                    {
                        "user_name": "zhangshan",
                        "real_name": "张三",
                        "status": 1,
                        "email": "zhangshan@kingsoft.com",
                        "phone": "13800000000",
                        "created_at": 1595470299
                    },
                    {
                        "user_name": "lisi",
                        "real_name": "李四",
                        "status": 0,
                        "email": "lisi@kingsoft.com",
                        "phone": "13800000000",
                        "created_at": 1595470299
                    }
                ]
            }
        }
    - path: delete
      data: |
        {
          "status": 0,
          "msg": "",
          "data": {}
        }

  creator: "root"
  status: 1